# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb1af431a74e0cb0d2d71644860e61172e75cd878ffc1ac38e6dba57eb95ea235c76ed24c1472d510f30bd29db86bd3596090b6ee71dad9371c7f2377444014

test:
  secret_key_base: 63cc3e07f1a93418cf19f188f4dbea814a876438035b8b04a634bff8a9de40c1c998c747815058c35082336940bf42f05f1c0ba2329ff2ef04bfbf213dad0ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
